"""Subclass of ipdialog, which is generated by wxFormBuilder."""

import wx
import dgx_gui

# Implementing ipdialog
class DGX syslogipdialog( dgx_gui.ipdialog ):
	def __init__( self, parent ):
		dgx_gui.ipdialog.__init__( self, parent )
	
