"""Subclass of DGXFrame, which is generated by wxFormBuilder."""

import wx
import dgx_gui

# Implementing DGXFrame
class DGX syslogDGXFrame( dgx_gui.DGXFrame ):
	def __init__( self, parent ):
		dgx_gui.DGXFrame.__init__( self, parent )
	
	# Handlers for DGXFrame events.
	def on_enable_logging( self, event ):
		# TODO: Implement on_enable_logging
		pass
	
	def on_disable_logging( self, event ):
		# TODO: Implement on_disable_logging
		pass
	
	
