"""Subclass of MainFrame, which is generated by wxFormBuilder."""

import wx
import dgx_gui

# Implementing MainFrame
class DGX syslogMainFrame( dgx_gui.MainFrame ):
	def __init__( self, parent ):
		dgx_gui.MainFrame.__init__( self, parent )
	
	# Handlers for MainFrame events.
	def on_enable_logging( self, event ):
		# TODO: Implement on_enable_logging
		pass
	
	def on_disable_logging( self, event ):
		# TODO: Implement on_disable_logging
		pass
	
	
